const FETCH_DATA_PRODUK = "FETCH_DATA_PRODUK";
const FETCH_DETAIL_PRODUK = "FETCH_DETAIL_PRODUK"
const FETCH_USER_DETAIL = "FETCH_USER_DETAIL";

export { FETCH_DATA_PRODUK, FETCH_USER_DETAIL, FETCH_DETAIL_PRODUK };
